TASK:
  KIND: "Panoptic"
MODEL:
  META_ARCHITECTURE: "PanopticFPN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    USE_SEMANTIC_FEATURES: False
    RPN_HEAD: "SingleConvRPNHead"
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 9
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  SEMANTIC:
    USE_FPN: True
    SEMANTIC_HEAD: "UpsampleEqualSizeConvSum"
    UPSAMPLE_MODULE: "One3x3ReLU"
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    COLLAPSE_THING_ONTOLOGY: False
    UPSAMPLE_METHOD: "bilinear"
    NUM_CLASSES: 11
  PANOPTIC:
    INSTANCE_WEIGHT: 1.0
    SEMANTIC_WEIGHT: 1.0
    COMPUTE_CC_RESULTS: False
    COMPUTE_PRE_RESULTS: False
  MASK_ON: True
DATASETS:
  TRAIN: ("panoptic_cityscapes_fine_instanceonly_seg_train_cocostyle",)
  TEST: ("panoptic_cityscapes_fine_instanceonly_seg_val_cocostyle",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (18000,)
  MAX_ITER: 24000
TEST:
  PREDICTION_PATHS: [] #["/scratch/jlazarow/experiments/panoptic/cityscapes/03152019_164312/inference/panoptic_cityscapes_fine_instanceonly_seg_val_cocostyle/predictions.pth"]
TEMPORARY_DIR: "/scratch/tmp"
NAME: "cityscapes"
DESCRIPTION: "dense ontology, finetuning from COCO"
