TASK:
  KIND: "Panoptic"
MODEL:
  META_ARCHITECTURE: "PanopticFPN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    USE_SEMANTIC_FEATURES: False
    RPN_HEAD: "SingleConvRPNHead"
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  ROI_ORDER_HEAD:
    OVERLAP_THRESHOLD: 0.10
    BATCH_SIZE_PER_IMAGE: 256
    SHARE_MASK_FEATURE_EXTRACTOR: False
    ENSURE_CONSISTENCY: True
    #ONLY_TRAIN: True
    WEIGHT: 1.0
  SEMANTIC:
    USE_FPN: True
    SEMANTIC_HEAD: "UpsampleEqualSizeConvSum"
    UPSAMPLE_MODULE: "One3x3ReLU"
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    COLLAPSE_THING_ONTOLOGY: False
    UPSAMPLE_METHOD: "bilinear"
  PANOPTIC:
    INSTANCE_WEIGHT: 1.0
    SEMANTIC_WEIGHT: 0.5
  FUSION:
    CONFIDENCE_THRESHOLD: 0.5
    OVERLAP_THRESHOLD: 0.5
    STUFF_MINIMUM_AREA: 4096
  MASK_ON: True
  ORDER_ON: False
  WEIGHT:  "/local/experiments/panoptic/order/06262019_200346/model_final.pth" #"/mnt/cube/jlazarow/experiments/panoptic/baseline/02112019_151538/model_final.pth" # "/local/experiments/panoptic/order/06222019_165802/model_final.pth" "/local/experiments/panoptic/order/06232019_143107/model_final.pth" # "/local/experiments/panoptic/order/06262019_111528/model_final.pth" #
DATASETS:
  TRAIN: ("panoptic_coco_2017_train",)
  TEST: ("panoptic_coco_2017_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  IMS_PER_BATCH: 4
  BASE_IMS_PER_BATCH: 8
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 120000)
  MAX_ITER: 91000
TEST:
  PREDICTION_PATHS: ["/local/experiments/panoptic/order/06262019_205807/inference/panoptic_coco_2017_val/predictions.pth"] #"/local/experiments/panoptic/order/06262019_132748/inference/panoptic_coco_2017_val/predictions.pth"] #"/local/experiments/panoptic/order/06252019_143058/inference/panoptic_coco_2017_val/predictions.pth"]
TEMPORARY_DIR: "/local/tmp/"
NAME: "order"
DESCRIPTION: "trying to fix everything but order head"
