TASK:
  KIND: "Panoptic"
MODEL:
  META_ARCHITECTURE: "PanopticFPN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    USE_SEMANTIC_FEATURES: False
    RPN_HEAD: "SingleConvRPNHead"
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  SEMANTIC:
    USE_FPN: True
    SEMANTIC_HEAD: "UpsampleEqualSizeConvSum"
    UPSAMPLE_MODULE: "One3x3ReLU"
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    COLLAPSE_THING_ONTOLOGY: False
    UPSAMPLE_METHOD: "bilinear"
  PANOPTIC:
    INSTANCE_WEIGHT: 1.0
    SEMANTIC_WEIGHT: 0.5
    COMPUTE_CC_RESULTS: False
  MASK_ON: True
  ORDER_ON: True
DATASETS:
  TRAIN: ("panoptic_coco_2017_train_overlap02",)
  TEST: ("panoptic_coco_2017_test_dev",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
TEST:
  CHUNK_PREDICTIONS: True
  PREDICTION_PATHS: [["/local/experiments/panoptic/order/03112019_222258/inference/panoptic_coco_2017_test_dev/file0.pth", "/local/experiments/panoptic/order/03112019_222258/inference/panoptic_coco_2017_test_dev/file1.pth", "/local/experiments/panoptic/order/03112019_222258/inference/panoptic_coco_2017_test_dev/file2.pth", "/local/experiments/panoptic/order/03112019_222258/inference/panoptic_coco_2017_test_dev/file3.pth"]]
  #PREDICTION_PATHS: [] #"/local/experiments/panoptic/03102019_151246/inference/panoptic_coco_2017_test_dev/predictions.pth"]
TEMPORARY_DIR: "/local/tmp"
NAME: "baseline"
DESCRIPTION: "for testdev from panoptic fusion baseline"
